---
kind: ConfigMap
apiVersion: v1
metadata:
  name: silent-auction-frontend
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
immutable: false
data:
  .env: |
    KEYCLOAK_CLIENT_ID=frontend
    KEYCLOAK_REALM=silent-auction
    KEYCLOAK_URL=https://keycloak-ingress-keycloak.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
    BACKEND_URL=http://silent-auction-backend:6443/api/v1
    MIN_TABLE_NUMBER=1
    MAX_TABLE_NUMBER=20
