---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - crunchy-instance.yaml
  - db-init-sql.yaml
  - pgadmin.yaml
  - service-account.yaml
  - services.yaml
  - secrets.yaml
  - configmaps.yaml
  - rollouts.yaml
  - tkn-pac-repos.yaml
images:
  - name: quay.io/ahussey/silent-auction/frontend
    digest: latest
  - name: quay.io/ahussey/silent-auction/backend
    digest: latest
