---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    postgres-operator.crunchydata.com/pgadmin: pgadmin
  ports:
    - name: pgadmin
      protocol: TCP
      port: 5050
      targetPort: pgadmin
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pgadmin
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  to:
    kind: Service
    name: pgadmin
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  subdomain: pgadmin-production
  path: /
  port:
    targetPort: pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-frontend-canary
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-frontend-stable
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: silent-auction-frontend
  namespace: production
spec:
  gateways:
    - silent-auction-frontend
  hosts:
    - silent-auction-frontend-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
  http:
    - name: silent-auction-frontend
      route:
        - destination:
            host: silent-auction-frontend-stable
          weight: 100
        - destination:
            host: silent-auction-frontend-canary
          weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: silent-auction-frontend
  namespace: production
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: silent-auction-frontend
        protocol: HTTP
      hosts:
        - silent-auction-frontend-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: silent-auction-frontend-canary
  namespace: production
spec:
  host: silent-auction-frontend-canary-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
  to:
    kind: Service
    name: silent-auction-frontend-canary
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: silent-auction-frontend-stable
  namespace: production
spec:
  host: silent-auction-frontend-stable-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
  to:
    kind: Service
    name: silent-auction-frontend-stable
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-backend-canary
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-backend
  ports:
    - name: http
      protocol: TCP
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: Service
metadata:
  name: silent-auction-backend-stable
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app.kubernetes.io/name: silent-auction-backend
  ports:
    - name: http
      protocol: TCP
      port: 6443
      targetPort: 6443
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: silent-auction-backend
  namespace: production
spec:
  gateways:
    - silent-auction-backend
  hosts:
    - silent-auction-backend-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
  http:
    - name: silent-auction-backend
      route:
        - destination:
            host: silent-auction-backend-stable
          weight: 100
        - destination:
            host: silent-auction-backend-canary
          weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: silent-auction-backend
  namespace: production
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: silent-auction-backend
        protocol: HTTP
      hosts:
        - silent-auction-backend-production.apps.rosa.grant-pub-prd.0r8r.p3.openshiftapps.com
