---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization-file
resources:
  - applications/cert-manager-operator.yaml
  - applications/crunchydata-operator.yaml
  - applications/devspaces-operator.yaml
  - applications/misc.yaml
  - applications/openshift-config.yaml
  - applications/pipelines-operator.yaml
  - applications/secrets-management.yaml
  - applications/rhbk-operator.yaml
  - applications/rhcl-instance.yaml
  - applications/rhcl-operator.yaml
  - applications/service-mesh-instance.yaml
  - applications/service-mesh-operator.yaml
