---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization-file
resources:
  # - applications/crunchydata-operator.yaml
  - applications/devspaces-operator.yaml
  - applications/misc.yaml
  - applications/pipelines-operator.yaml
  - applications/secrets-management.yaml
  # - applications/rhbk-operator.yaml
  # - applications/service-mesh-operator.yaml
